using System;
using System.Collections.Generic;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;

namespace Hanger51.EditorTools
{
    public static class Hanger51WorldCountrysideSetup
    {
        const string Root="Hanger 51 Surrounding Countryside", Airport="Hanger 51 Airport Complex", TerrainName="Hanger 51 Editable Terrain";
        const string Source="Assets/_Project/Environment/Terrain/Hanger51WorldTerrain.asset", Folder="Assets/_Project/Environment/Generated", Work=Folder+"/Hanger51CountrysideTerrain.asset";
        const int Seed=51051;
        struct Place { public string name; public Vector3 p; public float radius; public int buildings; }

        [MenuItem("Hanger 51/World/Current/96 - Build Surrounding Countryside")]
        public static void Build()
        {
            Terrain t=FindTerrain(); if(t==null){Debug.LogError("Step 96 could not find Hanger 51 Editable Terrain.");return;}
            EnsureFolder(Folder); TerrainData src=AssetDatabase.LoadAssetAtPath<TerrainData>(Source)??t.terrainData; TerrainData dst=AssetDatabase.LoadAssetAtPath<TerrainData>(Work);
            if(dst==null){dst=UnityEngine.Object.Instantiate(src);dst.name="Hanger 51 Countryside Terrain";AssetDatabase.CreateAsset(dst,Work);} t.terrainData=dst;
            GameObject airport=Find(Airport); Bounds ab=airport?BoundsOf(airport):new Bounds(t.transform.position+t.terrainData.size*.5f,new Vector3(700,80,700)); Vector3 c=ab.center; c.y=Ground(t,c); float clear=Mathf.Max(575,Mathf.Max(ab.extents.x,ab.extents.z)+260);
            GameObject old=Find(Root); if(old)Undo.DestroyObjectImmediate(old); GameObject root=new GameObject(Root); Undo.RegisterCreatedObjectUndo(root,"Build countryside");
            try{EditorUtility.DisplayProgressBar("Hanger 51 Countryside","Shaping terrain",.1f);Shape(t,src,dst,c,clear);var road=Mat("Road",new Color(.14f,.15f,.16f));var wall=Mat("Wall",new Color(.65f,.58f,.47f));var roof=Mat("Roof",new Color(.2f,.15f,.12f));var rock=Mat("Rock",new Color(.33f,.34f,.32f));var trunk=Mat("Trunk",new Color(.2f,.13f,.08f));var leaf=Mat("Leaves",new Color(.17f,.31f,.13f));
                EditorUtility.DisplayProgressBar("Hanger 51 Countryside","Building roads and settlements",.4f);BuildPlaces(t,root.transform,c,clear,road,wall,roof,out List<Place> places,out List<Vector3[]> roads);
                EditorUtility.DisplayProgressBar("Hanger 51 Countryside","Adding vegetation and rocks",.72f);Vegetation(t,src,root.transform,c,clear,places,roads,trunk,leaf,rock);
                t.Flush();EditorUtility.SetDirty(t.terrainData);EditorSceneManager.MarkSceneDirty(SceneManager.GetActiveScene());AssetDatabase.SaveAssets();EditorSceneManager.SaveOpenScenes();Selection.activeGameObject=root;Debug.Log("Step 96 complete: surrounding town/villages, roads, rolling terrain, trees, grass and rocks generated.",root);
            }finally{EditorUtility.ClearProgressBar();}
        }

        [MenuItem("Hanger 51/World/Current/97 - Validate Surrounding Countryside")]
        public static void Validate(){GameObject r=Find(Root);Terrain t=FindTerrain();if(!r||!t){Debug.LogError("Step 97 failed: run Step 96 first.");return;}int b=Count(r.transform,"Building "),rd=Count(r.transform,"Road Segment"),rocks=Count(r.transform,"Rock ");bool ok=b>=75&&rd>=30&&rocks>=20&&(t.terrainData.treeInstanceCount>0||Count(r.transform,"Tree ")>0);if(ok)Debug.Log($"Step 97 passed. buildings={b}, road segments={rd}, trees={t.terrainData.treeInstanceCount}, rocks={rocks}.",r);else Debug.LogError($"Step 97 failed. buildings={b}, road segments={rd}, trees={t.terrainData.treeInstanceCount}, rocks={rocks}.",r);}

        static void Shape(Terrain t,TerrainData src,TerrainData dst,Vector3 c,float clear){int n=dst.heightmapResolution;if(src.heightmapResolution!=n)return;float[,] a=src.GetHeights(0,0,n,n),h=new float[n,n];Vector3 o=t.transform.position,s=dst.size;for(int z=0;z<n;z++){float nz=z/(float)(n-1),wz=o.z+nz*s.z;for(int x=0;x<n;x++){float nx=x/(float)(n-1),wx=o.x+nx*s.x,d=Dist(new Vector3(wx,0,wz),c),blend=Mathf.SmoothStep(0,1,Mathf.InverseLerp(clear,clear+Mathf.Max(700,clear),d));float m=(Mathf.PerlinNoise(wx*.00045f+17,wz*.00045f+39)-.5f)*30+(Mathf.PerlinNoise(wx*.0011f+92,wz*.0011f+11)-.5f)*14;h[z,x]=Mathf.Clamp01(a[z,x]+m/Mathf.Max(1,s.y)*blend);}}dst.SetHeights(0,0,h);}

        static void BuildPlaces(Terrain t,Transform root,Vector3 c,float clear,Material road,Material wall,Material roof,out List<Place> places,out List<Vector3[]> roads){Transform pr=Child("Settlements",root),rr=Child("Road Network",root);places=new List<Place>{Make("Town - Ridgefield",t,c,new Vector2(.78f,.63f),Mathf.Max(1650,clear+800),270,52),Make("Village - Millbrook",t,c,new Vector2(-.82f,.57f),Mathf.Max(1250,clear+470),150,16),Make("Village - Ashford",t,c,new Vector2(.70f,-.83f),Mathf.Max(1350,clear+560),155,16),Make("Village - Pine Hollow",t,c,new Vector2(-.67f,-.76f),Mathf.Max(1450,clear+650),145,16)};roads=new List<Vector3[]>();Road(t,rr,c+(places[0].p-c).normalized*(clear+80),places[0].p,7,road,roads);Road(t,rr,places[0].p,places[1].p,6,road,roads);Road(t,rr,places[0].p,places[2].p,6,road,roads);Road(t,rr,places[1].p,places[3].p,5,road,roads);Road(t,rr,places[3].p,places[2].p,5,road,roads);var rng=new System.Random(Seed);foreach(Place q in places){Transform p=Child(q.name,pr);for(int i=0;i<q.buildings;i++){float a=Next(rng,0,Mathf.PI*2),r=Mathf.Sqrt(Next(rng,.1f,1))*q.radius;Vector3 x=q.p+new Vector3(Mathf.Cos(a)*r,0,Mathf.Sin(a)*r);x.y=Ground(t,x);Building(p,x,Next(rng,9,18),Next(rng,9,16),Next(rng,5,11),Next(rng,0,360),wall,roof,i);}}}
        static Place Make(string name,Terrain t,Vector3 c,Vector2 d,float dist,float r,int b){d.Normalize();Vector3 p=c+new Vector3(d.x*dist,0,d.y*dist);Vector3 o=t.transform.position,s=t.terrainData.size;float m=Mathf.Min(200,Mathf.Min(s.x,s.z)*.06f);p.x=Mathf.Clamp(p.x,o.x+m,o.x+s.x-m);p.z=Mathf.Clamp(p.z,o.z+m,o.z+s.z-m);p.y=Ground(t,p);return new Place{name=name,p=p,radius=r,buildings=b};}
        static void Road(Terrain t,Transform parent,Vector3 a,Vector3 b,float width,Material mat,List<Vector3[]> paths){int n=Mathf.Max(4,Mathf.CeilToInt(Vector3.Distance(a,b)/45));Vector3[] p=new Vector3[n+1];for(int i=0;i<=n;i++){p[i]=Vector3.Lerp(a,b,i/(float)n);p[i].y=Ground(t,p[i])+.08f;}paths.Add(p);Transform r=Child("Road",parent);for(int i=0;i<n;i++){Vector3 d=p[i+1]-p[i];GameObject g=GameObject.CreatePrimitive(PrimitiveType.Cube);g.name=$"Road Segment {i+1:000}";g.transform.SetParent(r,false);g.transform.position=(p[i]+p[i+1])*.5f;g.transform.rotation=Quaternion.LookRotation(d.normalized,Vector3.up);g.transform.localScale=new Vector3(width,.08f,d.magnitude+.2f);g.GetComponent<Renderer>().sharedMaterial=mat;UnityEngine.Object.DestroyImmediate(g.GetComponent<Collider>());}}
        static void Building(Transform p,Vector3 x,float w,float d,float h,float yaw,Material wall,Material roof,int i){Transform r=Child($"Building {i+1:00}",p);r.position=x;r.rotation=Quaternion.Euler(0,yaw,0);GameObject b=GameObject.CreatePrimitive(PrimitiveType.Cube);b.transform.SetParent(r,false);b.transform.localPosition=new Vector3(0,h*.5f,0);b.transform.localScale=new Vector3(w,h,d);b.GetComponent<Renderer>().sharedMaterial=wall;GameObject q=GameObject.CreatePrimitive(PrimitiveType.Cube);q.transform.SetParent(r,false);q.transform.localPosition=new Vector3(0,h+.5f,0);q.transform.localScale=new Vector3(w*1.08f,1,d*1.08f);q.GetComponent<Renderer>().sharedMaterial=roof;}

        static void Vegetation(Terrain t,TerrainData src,Transform root,Vector3 c,float clear,List<Place> places,List<Vector3[]> roads,Material trunk,Material leaf,Material rock){TerrainData d=t.terrainData;var rng=new System.Random(Seed+9);if(d.treePrototypes.Length>0){var trees=new List<TreeInstance>(src.treeInstances);int wanted=900;for(int a=0;a<12000&&wanted>0;a++){float nx=Next(rng,.02f,.98f),nz=Next(rng,.02f,.98f);Vector3 p=new Vector3(t.transform.position.x+nx*d.size.x,0,t.transform.position.z+nz*d.size.z);if(!Open(p,c,clear,places,roads)||Mathf.PerlinNoise(p.x*.0012f,p.z*.0012f)<.5f)continue;float s=Next(rng,.8f,1.35f);trees.Add(new TreeInstance{position=new Vector3(nx,d.GetInterpolatedHeight(nx,nz)/Mathf.Max(1,d.size.y),nz),prototypeIndex=rng.Next(d.treePrototypes.Length),widthScale=s,heightScale=s,rotation=Next(rng,0,Mathf.PI*2),color=Color.white,lightmapColor=Color.white});wanted--;}d.treeInstances=trees.ToArray();}else{Transform f=Child("Fallback Vegetation",root);for(int i=0;i<120;i++){Vector3 p=RandPoint(rng,t);if(!Open(p,c,clear,places,roads))continue;Tree(f,p,trunk,leaf,i);}}
            if(d.detailPrototypes.Length>0){int layer=0,w=d.detailWidth,h=d.detailHeight;int[,] map=src.detailWidth==w&&src.detailHeight==h&&src.detailPrototypes.Length>0?src.GetDetailLayer(0,0,w,h,layer):new int[h,w];for(int z=0;z<h;z+=2)for(int x=0;x<w;x+=2){Vector3 p=new Vector3(t.transform.position.x+x/(float)w*d.size.x,0,t.transform.position.z+z/(float)h*d.size.z);if(Open(p,c,clear+50,places,roads)&&Mathf.PerlinNoise(p.x*.002f,p.z*.002f)>.42f)map[z,x]=Mathf.Max(map[z,x],2);}d.SetDetailLayer(0,0,layer,map);}Transform rp=Child("Rocks",root);int made=0;for(int a=0;a<500&&made<65;a++){Vector3 p=RandPoint(rng,t);if(!Open(p,c,clear+70,places,roads))continue;GameObject r=GameObject.CreatePrimitive(PrimitiveType.Sphere);r.name=$"Rock {made+1:000}";r.transform.SetParent(rp,false);r.transform.position=p+.15f*Vector3.up;r.transform.localScale*=Next(rng,.8f,3);r.transform.rotation=Quaternion.Euler(Next(rng,-20,20),Next(rng,0,360),Next(rng,-20,20));r.GetComponent<Renderer>().sharedMaterial=rock;UnityEngine.Object.DestroyImmediate(r.GetComponent<Collider>());made++;}}
        static bool Open(Vector3 p,Vector3 c,float clear,List<Place> places,List<Vector3[]> roads){if(Dist(p,c)<clear)return false;foreach(Place q in places)if(Dist(p,q.p)<q.radius+30)return false;foreach(Vector3[] r in roads)for(int i=0;i<r.Length-1;i++)if(SegDist(p,r[i],r[i+1])<12)return false;return true;}
        static Vector3 RandPoint(System.Random r,Terrain t){Vector3 o=t.transform.position,s=t.terrainData.size;Vector3 p=new Vector3(o.x+Next(r,.02f,.98f)*s.x,0,o.z+Next(r,.02f,.98f)*s.z);p.y=Ground(t,p);return p;}
        static void Tree(Transform p,Vector3 x,Material trunk,Material leaf,int i){Transform r=Child($"Tree {i+1:000}",p);r.position=x;GameObject a=GameObject.CreatePrimitive(PrimitiveType.Cylinder);a.transform.SetParent(r,false);a.transform.localPosition=new Vector3(0,3,0);a.transform.localScale=new Vector3(.4f,3,.4f);a.GetComponent<Renderer>().sharedMaterial=trunk;UnityEngine.Object.DestroyImmediate(a.GetComponent<Collider>());GameObject b=GameObject.CreatePrimitive(PrimitiveType.Sphere);b.transform.SetParent(r,false);b.transform.localPosition=new Vector3(0,7,0);b.transform.localScale=new Vector3(4,5,4);b.GetComponent<Renderer>().sharedMaterial=leaf;UnityEngine.Object.DestroyImmediate(b.GetComponent<Collider>());}

        static Terrain FindTerrain(){GameObject g=Find(TerrainName);Terrain t=g?(g.GetComponent<Terrain>()??g.GetComponentInChildren<Terrain>(true)):null;if(t)return t;Terrain[] a=UnityEngine.Object.FindObjectsByType<Terrain>(FindObjectsInactive.Include,FindObjectsSortMode.None);return a.Length>0?a[0]:null;}
        static GameObject Find(string n){GameObject g=GameObject.Find(n);if(g)return g;foreach(Transform t in UnityEngine.Object.FindObjectsByType<Transform>(FindObjectsInactive.Include,FindObjectsSortMode.None))if(t&&t.name==n&&t.gameObject.scene.IsValid())return t.gameObject;return null;}
        static Bounds BoundsOf(GameObject g){bool set=false;Bounds b=new Bounds(g.transform.position,Vector3.zero);foreach(Renderer r in g.GetComponentsInChildren<Renderer>(true)){if(!set){b=r.bounds;set=true;}else b.Encapsulate(r.bounds);}foreach(Collider c in g.GetComponentsInChildren<Collider>(true)){if(!set){b=c.bounds;set=true;}else b.Encapsulate(c.bounds);}return b;}
        static float Ground(Terrain t,Vector3 p)=>t.SampleHeight(p)+t.transform.position.y;static float Dist(Vector3 a,Vector3 b){float x=a.x-b.x,z=a.z-b.z;return Mathf.Sqrt(x*x+z*z);}static float Next(System.Random r,float a,float b)=>a+(float)r.NextDouble()*(b-a);static float SegDist(Vector3 p,Vector3 a,Vector3 b){Vector2 q=new Vector2(p.x,p.z),x=new Vector2(a.x,a.z),d=new Vector2(b.x-a.x,b.z-a.z);return d.sqrMagnitude<.001f?Vector2.Distance(q,x):Vector2.Distance(q,x+d*Mathf.Clamp01(Vector2.Dot(q-x,d)/d.sqrMagnitude));}
        static Transform Child(string n,Transform p){GameObject g=new GameObject(n);g.transform.SetParent(p,false);return g.transform;}static int Count(Transform r,string n){int c=0;foreach(Transform t in r.GetComponentsInChildren<Transform>(true))if(t!=r&&t.name.Contains(n))c++;return c;}
        static Material Mat(string n,Color c){string mf=Folder+"/Materials";EnsureFolder(mf);string path=mf+"/"+n+".mat";Material m=AssetDatabase.LoadAssetAtPath<Material>(path);if(!m){Shader s=Shader.Find("Universal Render Pipeline/Lit")??Shader.Find("Standard");m=new Material(s){name=n};AssetDatabase.CreateAsset(m,path);}m.color=c;if(m.HasProperty("_BaseColor"))m.SetColor("_BaseColor",c);return m;}
        static void EnsureFolder(string path){string[] p=path.Split('/');string cur=p[0];for(int i=1;i<p.Length;i++){string n=cur+"/"+p[i];if(!AssetDatabase.IsValidFolder(n))AssetDatabase.CreateFolder(cur,p[i]);cur=n;}}
    }
}
