using Hanger51.Aircraft;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;

namespace Hanger51.EditorTools
{
    public static class P51WingArmamentAudioSetup
    {
        private const string AircraftRootName = "P-51D Mustang Test Aircraft";
        private const string ArmamentRootName = "P-51 Serviceable Wing Armament";

        [MenuItem("Hanger 51/P-51 Mustang/40 - Add 3D Armament and Service Audio")]
        public static void AddArmamentAudio()
        {
            if (EditorApplication.isPlaying)
            {
                Debug.LogError("P-51 Step 40 failed. Exit Play mode first.");
                return;
            }
            if (EditorApplication.isCompiling)
            {
                Debug.LogError("P-51 Step 40 failed. Wait for Unity to finish compiling.");
                return;
            }

            Scene scene = SceneManager.GetActiveScene();
            GameObject aircraft = GameObject.Find(AircraftRootName);
            if (!scene.IsValid() || string.IsNullOrWhiteSpace(scene.path) || aircraft == null)
            {
                Debug.LogError("P-51 Step 40 failed. Open the saved hangar scene containing the P-51 first.");
                return;
            }

            P51WingArmamentSystem system = aircraft.GetComponent<P51WingArmamentSystem>();
            Transform armamentRoot = aircraft.transform.Find(ArmamentRootName);
            if (system == null || armamentRoot == null)
            {
                Debug.LogError("P-51 Step 40 failed. The serviceable wing armament system is missing.", aircraft);
                return;
            }

            Transform[] muzzles = ReadTransformArray(system, "muzzles", 6);
            Transform[] ejectionPorts = ReadTransformArray(system, "ejectionPorts", 6);
            Transform[] panelPivots = ReadTransformArray(system, "panelPivots", 2);
            Transform[] gunServicePoints = new Transform[6];
            Transform[] ammoServicePoints = new Transform[6];

            P51WingArmamentServicePoint[] servicePoints =
                armamentRoot.GetComponentsInChildren<P51WingArmamentServicePoint>(true);
            for (int index = 0; index < servicePoints.Length; index++)
            {
                P51WingArmamentServicePoint point = servicePoints[index];
                if (point == null) continue;
                int station = Mathf.Clamp(point.StationIndex, 0, 5);
                if (point.ServiceKind == P51WingArmamentServiceKind.GunMount)
                {
                    gunServicePoints[station] = point.transform;
                }
                else if (point.ServiceKind == P51WingArmamentServiceKind.AmmoBay)
                {
                    ammoServicePoints[station] = point.transform;
                }
            }

            int missingMuzzles = CountNull(muzzles);
            int missingGunPoints = CountNull(gunServicePoints);
            int missingAmmoPoints = CountNull(ammoServicePoints);
            if (missingMuzzles > 0 || missingGunPoints > 0 || missingAmmoPoints > 0)
            {
                Debug.LogError(
                    $"P-51 Step 40 failed. Missing references: muzzles={missingMuzzles}, gun service points={missingGunPoints}, ammo service points={missingAmmoPoints}. "
                    + "Run Steps 38 and 39 first so the real gun muzzle anchors and fitted service stations are present.",
                    aircraft);
                return;
            }

            P51WingArmamentAudioController controller = aircraft.GetComponent<P51WingArmamentAudioController>();
            if (controller == null)
            {
                controller = Undo.AddComponent<P51WingArmamentAudioController>(aircraft);
            }
            controller.Configure(
                system,
                muzzles,
                ejectionPorts,
                panelPivots,
                gunServicePoints,
                ammoServicePoints);
            EditorUtility.SetDirty(controller);

            EditorSceneManager.MarkSceneDirty(scene);
            AssetDatabase.SaveAssets();
            if (!EditorSceneManager.SaveScene(scene))
            {
                Debug.LogError("P-51 Step 40 configured armament audio but Unity could not save the scene.");
                return;
            }

            Hanger51BuildTools.PrepareCurrentSceneForBuild(false);
            Debug.Log(
                "P-51 Step 40 complete. Added procedural 3D six-gun report/mechanical audio at the real muzzle anchors, "
                + "physical casing-impact clinks, wing-panel hinge/latch sounds, and gun/ammo service ratchet/thud sounds. "
                + "All audio is generated by the game at runtime, so there are no external sound-file or license dependencies.",
                aircraft);
        }

        [MenuItem("Hanger 51/P-51 Mustang/41 - Validate 3D Armament Audio")]
        public static void ValidateArmamentAudio()
        {
            bool passed = true;
            GameObject aircraft = GameObject.Find(AircraftRootName);
            if (aircraft == null)
            {
                Debug.LogError("P-51 Step 41 failed: P-51 aircraft is missing.");
                return;
            }

            P51WingArmamentSystem system = aircraft.GetComponent<P51WingArmamentSystem>();
            P51WingArmamentAudioController controller = aircraft.GetComponent<P51WingArmamentAudioController>();
            if (system == null)
            {
                Debug.LogError("P-51 Step 41 failed: wing armament system is missing.");
                passed = false;
            }
            if (controller == null || !controller.IsConfigured)
            {
                Debug.LogError("P-51 Step 41 failed: procedural 3D armament audio controller is missing or incomplete.");
                passed = false;
            }

            if (system != null)
            {
                Transform[] muzzles = ReadTransformArray(system, "muzzles", 6);
                int actualMuzzleAnchors = 0;
                for (int index = 0; index < muzzles.Length; index++)
                {
                    if (muzzles[index] != null && muzzles[index].name == "Actual Gun Muzzle Anchor")
                    {
                        actualMuzzleAnchors++;
                    }
                }
                if (actualMuzzleAnchors != 6)
                {
                    Debug.LogError($"P-51 Step 41 failed: expected 6 actual physical gun muzzle anchors, found {actualMuzzleAnchors}.");
                    passed = false;
                }
            }

            AudioListener[] listeners = Object.FindObjectsByType<AudioListener>(FindObjectsInactive.Include, FindObjectsSortMode.None);
            if (listeners.Length == 0)
            {
                Debug.LogError("P-51 Step 41 failed: no AudioListener exists in the scene, so 3D sound cannot be heard.");
                passed = false;
            }

            if (passed)
            {
                Debug.Log(
                    $"P-51 Step 41 passed. Procedural 3D armament audio is configured at all six physical gun muzzles; AudioListeners={listeners.Length}. "
                    + "Gunfire, mechanical action, casing impacts, panel hinge/latch, ratchet, and installation thuds are ready.");
            }
        }

        private static Transform[] ReadTransformArray(P51WingArmamentSystem system, string propertyName, int length)
        {
            Transform[] result = new Transform[length];
            SerializedObject serialized = new SerializedObject(system);
            SerializedProperty property = serialized.FindProperty(propertyName);
            if (property == null || !property.isArray) return result;
            int count = Mathf.Min(length, property.arraySize);
            for (int index = 0; index < count; index++)
            {
                result[index] = property.GetArrayElementAtIndex(index).objectReferenceValue as Transform;
            }
            return result;
        }

        private static int CountNull(Transform[] values)
        {
            int count = 0;
            if (values == null) return 1;
            for (int index = 0; index < values.Length; index++)
            {
                if (values[index] == null) count++;
            }
            return count;
        }
    }
}
